name: Release

on:
  push:
    branches:
      - master

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        shell: powershell
        run: choco install nasm

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc
          profile: minimal
          override: true

      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-
            
      - name: Cache cargo index
        uses: actions/cache@v3
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-git-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-git-
            
      - name: Cache cargo build
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-target-

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target=x86_64-pc-windows-msvc

      - name: Get version
        id: get_version
        run: |
          $version = ((Get-Content -Path .\Cargo.toml -Raw) -split "`n") -match "^version" | %{ $_ -replace '^version = "', '' } | %{ $_ -replace '"', '' }
          echo "VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Create GNU Directory
        run: |
          mkdir ./target/x86_64-pc-windows-gnu/release

      - name: Create GNU zip
        run: Compress-Archive -Path ./target/x86_64-pc-windows-gnu/release/CaptchaCam.exe -DestinationPath ./target/x86_64-pc-windows-gnu/release/captchacam-${{ env.VERSION }}-pc-windows-gnu.zip

      - name: Create MSVC zip
        run: Compress-Archive -Path ./target/x86_64-pc-windows-msvc/release/CaptchaCam.exe -DestinationPath ./target/x86_64-pc-windows-msvc/release/captchacam-${{ env.VERSION }}-pc-windows-msvc.zip

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
